### ISSUE TITLE
Allow PHP 8.1

### ISSUE THREAD

**Issue by fnagel** [undkonsorten/taskqueue#3]
Despite the last tag has "[release hotfix version for php 8.1](https://github.com/undkonsorten/taskqueue/commit/b84f566da791fcef032f42ecc22742448bb032f9)" as a commit message, it's not possible to install the extension using composer with  PHP 8. Is that on purpose?

https://github.com/undkonsorten/taskqueue/blob/main/composer.json#L38

**Comment by Starkmann** [comment]
Should be fixed with: 77abf8e700beb8bad9556a317369c4e27c9953ab
