### ISSUE TITLE
TYPO3 v12

### ISSUE THREAD

**Issue by devtroll** [undkonsorten/taskqueue#7]
Hey!

Do you plan a release for TYPO3 v12?

Thanks :-)

**Comment by Starkmann** [comment]
There will be a release for 12. But right now i have no schedule for this.
With 12 i would also like to integrate the new messenger feature.
 See: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.2/Feature-97700-AdoptSymfonyMessengerAsAMessageBusAndQueue.html

So this might become a bigger release than rather just compatibility, but still not 100% sure, maybe i split this in two releases.

**Comment by devtroll** [comment]
Thanks for your information about this topic. In my mind it would be better, to split it into two releases, because all in one release is a huge workload and we all need v12 support :-)

You do a great work!

**Comment by Starkmann** [comment]
Release 9.0.0 is now out for TYPO3 12
