### ISSUE TITLE
TaskRepository :: Task ordering

### ISSUE THREAD

**Issue by LinkPool2** [undkonsorten/taskqueue#9]
TaskRepository.php

change the orderings in the TaskRepository.ph from:

```
        $orderings = [
            'priority' => QueryInterface::ORDER_DESCENDING,
            'tstamp' => QueryInterface::ORDER_DESCENDING
        ];
```
to:

```
$orderings = [
     'priority' => QueryInterface::ORDER_DESCENDING,
     'retries' => QueryInterface::ORDER_ASCENDING,
     'uid' => QueryInterface::ORDER_ASCENDING
]; 
```

so, the oldest tasks would be done at first.

**Comment by Starkmann** [comment]
This feature is now available in develop, if everything  fine i would merge it and create a release.

**Comment by LinkPool2** [comment]
Tested with TYPO3 11.5 
10.000 Mails, 500 Mails per Cycle, 1 Cycle every 5 Minute

**Comment by LinkPool2** [comment]
done
